Adding hydrate macro & added documentation
algolia/laravel-scout-algolia-macros pull request #10
Opened 2017-07-26 11:42 UTC by robbydooo

Discussed in issue #8 

Adding hydrate macro to hydrate models from the algolia index vs database lookups after a search has been completed.

Credit to @aaronhuisinga for suggesting un-guarding for mass assignment.

2017-07-26 14:23 UTC, aaronhuisinga commented on README.md
> +    public function getRankingInfoAttribute(): array
According to the composer.json file, this package doesn't specify a minimum PHP version. Is using return types like this in the documentation something the Algolia team wants?

2017-07-26 15:05 UTC, robbydooo commented on README.md
> +    public function getRankingInfoAttribute(): array
I guess this package is dependant on the Scout library given it is Macros specifically for this. Possibly why PHP version is omitted.

Entirely up to the Algolia team how they feel about these examples in the docs. I was going for the better to have docs than not have docs at all ideology :-)

2017-07-26 15:45 UTC, julienbourdeau requested changes
I assume you are using the result in your views? Have you considered frontend search?

I wonder if it wouldn't be easier to have something only for `_highlightedResults` or `_rankingInfos`. Something like

```php
People::search('test')
              ->with(['hitsPerPage' => 30])
              ->include(['_highlightedResults'])
              ->return(); // I wish we could have get() here
```

I'd like to avoid having to edit multiple model to override the fill method.

2017-07-26 15:45 UTC, julienbourdeau commented on README.md
> +    public function getRankingInfoAttribute(): array
You're write we can't do that. We have to stick to [Scout version](https://github.com/laravel/scout/blob/3.0/composer.json#L21).

2017-07-26 15:45 UTC, julienbourdeau commented on README.md
> +## `with`
Thanks for the doc. 👍 
If you want to get it merged quickly, you can create a separate PR 👌

2017-07-26 22:24 UTC, robbydooo commented on README.md
> +## `with`
With regards to the using results in the view, yes they are being used in the view as they need to be rendered in to the page and not client side generated as they are core parts of the  page content for SEO purposes. It also keeps our number of requests down to improve overall page performance.

2017-07-27 10:39 UTC, robbydooo commented on README.md
> +## `with`
To be clear on usage, there are plenty of situations you need access to algolia search results in back end code. For example we are using algolia to pull in the nearest accommodations based around a lat/lon and rating and need hydrated models so we can then call methods on those results like generateUrl() or $accommodation->getLocation() etc.

2017-07-27 13:02 UTC, julienbourdeau commented
@robbydooo  I reconsidered this PR, I think it will be a great addition. Following @aaronhuisinga's recommendation, once the model is ungarded, everything will be filed so you dont have to modify each model. 
If you want to avoid some attributes you can either use `$garded` or algolia's `restrictRetrievableAttributes`.

I will merge and update the doc.

Thank you guys for your contribution 👍

2017-07-27 13:02 UTC, julienbourdeau approved these changes

2017-07-27 13:03 UTC, merged

2017-07-27 13:52 UTC, julienbourdeau commented
@robbydooo @aaronhuisinga I edited the doc and opened this PR: https://github.com/algolia/laravel-scout-algolia-macros/pull/11

Feel free to review it :)

2017-07-27 16:19 UTC, robbydooo commented
Looks good, glad you reconsidered 👍 , thanks to both of you for your input and approval.