feat(ua): Add custom UA suffix
algolia/laravel-scout-algolia-macros pull request #13
Opened 2017-09-08 16:07 UTC by julienbourdeau

2017-09-08 16:09 UTC, Haroenv commented on src/ServiceProvider.php
> +        AlgoliaUserAgent::addSuffixUserAgentSegment('; Laravel Scout macros package', '0.x');
Shouldn't this be a prefix?

2017-09-08 16:10 UTC, julienbourdeau commented on src/ServiceProvider.php
> +        AlgoliaUserAgent::addSuffixUserAgentSegment('; Laravel Scout macros package', '0.x');
I thought it was from the most important to the less important. Is there a special order?

2017-09-08 16:19 UTC, Haroenv commented on src/ServiceProvider.php
> +        AlgoliaUserAgent::addSuffixUserAgentSegment('; Laravel Scout macros package', '0.x');
We should get that in the spec, I thought it was a dependency chain (macros; ...; php)

2017-09-08 16:25 UTC, julienbourdeau commented on src/ServiceProvider.php
> +        AlgoliaUserAgent::addSuffixUserAgentSegment('; Laravel Scout macros package', '0.x');
¯\_(ツ)_/¯ haha

2017-09-09 09:08 UTC, rayrutjes requested changes
Can we add some tests maybe?

2017-09-11 08:25 UTC, julienbourdeau commented on src/ServiceProvider.php
> +        AlgoliaUserAgent::addSuffixUserAgentSegment('; Laravel Scout macros package', '0.x');
Actually your way would make more sense. As soon as you read "scout settings integration". You know scout and php client are used underneath.

2018-02-09 10:31 UTC, julienbourdeau commented
I will add tests as soon as possible, I'll merge this one for now. I created https://github.com/algolia/laravel-scout-algolia-macros/issues/16 for the test suite.

2018-02-09 10:31 UTC, merged